### PR TITLE
Update to show support for Django 4.2 and Python up to 3.11

### PR DESCRIPTION
**Pull request by StevenMapes**
Updating the README with a table to display the Python/Django support so that it's easier to read for users.

I would suggest that Python 3.5 and 3.6 alongside Django 2.2 be dropped as being officially supported due to them being past their EOL unless you require them yourself. Whilst the project does work with them dropping them would also allow the requirements to be updated including Fido2 to 1.0.0, #44,  though the project should also be tested for compatibility with the forthcoming 1.1.0

*UPDATE*

I've now included updating  the project to show support for Python 3.11 and Django 4.2 the latter was released today but I have completed my tests to check that everything is working

### CODE REVIEW

**Comment by StevenMapes** [comment]
Updated my PR to include the changes to show the project works with Python through 3.11 and Django through 4.2 so this will close Issue #60

**Comment by StevenMapes** [comment]
@oliwarner - I've updated the pyproject.toml file to also include the support for Python 3.11 and Django 4.2 and to put the version on 0.5.5 which is the latest released version on pypi - https://pypi.org/project/django-multifactor/#history

If you could review my changes and, if you are happy,  merge and release those as 0.5.6 that would be great as then other people will be able to install this onto Django 4. 2 projects without having to fork it first as I am

**Comment by oliwarner** [comment]
I need to have a play around with this locally.

Busy this weekend but should have some time next week, should have some time to dig into the FIDO upgrade. Also want to bolt on some automated testing so we can hook in CI/CD and take me out of the loop when little updates like this need to happen.

**Comment by StevenMapes** [comment]
Sounds good to me. It was on my list to try to setup tox, matrix of tests and GitHub auctions to try to add in automated testing as it'll definitely improve things 🙂

**Pull request merged**
